name: Build and Deploy Node.js App to Azure

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the app (if applicable)
      # Uncomment the next line if you have a build step
      # - name: Build the app
      #   run: npm run build

      # Step 5: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <YOUR_AZURE_APP_NAME>  # Replace with your Azure App Service name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Add your publish profile as a secret
          package: .  # Path to your app's package (current directory)
